### ISSUE TITLE
风止于秋水,我止于你 | AEIOU

### ISSUE THREAD

**Issue by Peachfart** [Peachfart/aeiou.github.io.old#1]
https://aeiou.space/post/feng-zhi-yu-qiu-shui-wo-zhi-yu-ni/ 

 ​“其实，我也没有那么深情，你也没有那么难忘。可是再难心动，毕竟年少不再”		——网易云热评《那些你很冒险的梦》

​想谈一场啰里八嗦的恋爱，每天说甜死人的话，约你来我家吃西瓜，和你一起在下完雨的半夜穿着拖鞋出溜达，坐在马路牙子上喝冰啤酒，...

**Comment by onepluskiller** [comment]
风止于秋水,我止于你
