### ISSUE TITLE
我那么喜欢你,你喜欢我一下会死啊? | AEIOU

### ISSUE THREAD

**Issue by Peachfart** [Peachfart/aeiou.github.io.old#2]
https://aeiou.space/post/wo-na-me-xi-huan-ni-ni-xi-huan-wo-yi-xia-hui-si-a/ 

 

曾经有一份真诚的爱情放在我面前，我没有珍惜，等我失去的时候我才后悔莫及，人世间最痛苦的事莫过于此。 如果上天能够给我一个再来一次的机会，我会对那个女孩子说三个字：我爱你。 如果非要在这份爱上加上一个期限，我希望是一万年。  --出自电影...

**Comment by onepluskiller** [comment]
我那么喜欢你,你喜欢我一下会死啊?
