### ISSUE TITLE
面朝大海，春暖花开 | AEIOU

### ISSUE THREAD

**Issue by Peachfart** [Peachfart/aeiou.github.io.old#3]
https://aeiou.space/post/mian-zhao-da-hai-chun-nuan-hua-kai/ 

 《面朝大海，春暖花开》
海子
从明天起，做一个幸福的人
喂马，劈柴，周游世界
从明天起，关心粮食和蔬菜
我有一所房子，
面朝大海，春暖花开
从明天起，
和每一个亲人通信
告诉他们我的幸福
那幸福的闪电告诉我的
我将告诉每一个人
给每一条河每...

**Comment by onepluskiller** [comment]
面朝大海，春暖花开
